export const LOAD_ROUTES = 'LOAD_ROUTES';
export const UPDATE_ROUTE = 'UPDATE_ROUTE';
export const ADD_ROUTE = 'ADD_ROUTE';

export const LOAD_SECTORS = 'LOAD_SECTORS';

export const SAVE_USER = 'SAVE_USER';

export const CHANGE_TAB = 'CHANGE_TAB';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const INC_NUM_OF_ACTIVE_REQUESTS = 'INC_NUM_OF_ACTIVE_REQUESTS';
export const DEC_NUM_OF_ACTIVE_REQUESTS = 'DEC_NUM_OF_ACTIVE_REQUESTS';

export const SET_SELECTED_PAGE = 'SET_SELECTED_PAGE';
export const SET_DEFAULT_SELECTED_PAGES = 'SET_DEFAULT_SELECTED_PAGES';

export const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER';
export const SET_DEFAULT_SELECTED_FILTERS = 'SET_DEFAULT_SELECTED_FILTERS';
export const LOAD_FROM_LOCAL_STORAGE_SELECTED_FILTERS = 'LOAD_FROM_LOCAL_STORAGE_SELECTED_FILTERS';

export const LOAD_ROUTE_MARK_COLORS = 'LOAD_ROUTE_MARK_COLORS';
