export const SET_ROUTES = 'SET_ROUTES';
export const SET_ROUTE = 'SET_ROUTE';
export const SET_ROUTE_DATA = 'SET_ROUTE_DATA';
export const SET_ROUTE_PROPERTY = 'SET_ROUTE_PROPERTY';
export const REMOVE_ROUTE_PROPERTY_BY_ID = 'REMOVE_ROUTE_PROPERTY_BY_ID';
export const SET_ROUTES_DATA = 'SET_ROUTES_DATA';
export const REMOVE_ROUTE = 'REMOVE_ROUTE';
export const SET_ROUTE_IDS = 'SET_ROUTE_IDS';

export const SET_SECTORS = 'SET_SECTORS';
export const SET_SECTOR = 'SET_SECTOR';
export const SET_SECTOR_IDS = 'SET_SECTOR_IDS';

export const SET_USERS = 'SET_USERS';
export const SAVE_USER = 'SAVE_USER';

export const CHANGE_TAB = 'CHANGE_TAB';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const REMOVE_TOKEN = 'REMOVE_TOKEN';

export const INC_NUM_OF_ACTIVE_REQUESTS = 'INC_NUM_OF_ACTIVE_REQUESTS';
export const DEC_NUM_OF_ACTIVE_REQUESTS = 'DEC_NUM_OF_ACTIVE_REQUESTS';

export const SET_SELECTED_PAGE = 'SET_SELECTED_PAGE';
export const SET_DEFAULT_SELECTED_PAGES = 'SET_DEFAULT_SELECTED_PAGES';

export const SET_SELECTED_VIEW_MODE = 'SET_SELECTED_VIEW_MODE';

export const SET_SELECTED_FILTER = 'SET_SELECTED_FILTER';
export const SET_DEFAULT_SELECTED_FILTERS = 'SET_DEFAULT_SELECTED_FILTERS';
export const LOAD_FROM_LOCAL_STORAGE_SELECTED_FILTERS = 'LOAD_FROM_LOCAL_STORAGE_SELECTED_FILTERS';

export const LOAD_ROUTE_MARK_COLORS = 'LOAD_ROUTE_MARK_COLORS';
