export const LOAD_SECTORS_REQUEST = 'LOAD_SECTORS_REQUEST';
export const LOAD_SECTORS_FAILED = 'LOAD_SECTORS_FAILED';
export const LOAD_SECTOR_SUCCESS = 'LOAD_SECTOR_SUCCESS';
export const LOAD_SECTORS = 'LOAD_SECTORS';
