export const LOAD_ROUTE_MARK_COLORS_REQUEST = 'LOAD_ROUTE_MARK_COLORS_REQUEST';
export const LOAD_ROUTE_MARK_COLORS_FAILED = 'LOAD_ROUTE_MARK_COLORS_FAILED';
export const LOAD_ROUTE_MARK_COLORS_SUCCESS = 'LOAD_ROUTE_MARK_COLORS_SUCCESS';
