import { StyleSheet } from '../../aphrodite';

const styles = StyleSheet.create({
  cardM: {
    width: '100%',
    padding: '12px',
    boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.08)',
    transition: 'box-shadow .4s ease-out',
    display: 'flex',
    textDecoration: 'none',
    boxSizing: 'border-box',
    outline: 'none',
    backgroundColor: '#FFFFFF',
    marginBottom: '20px',
    position: 'relative',
    ':hover': { boxShadow: '0px 8px 8px rgba(0, 0, 0, 0.12)' },
    ':focus': { boxShadow: '0px 8px 8px rgba(0, 0, 0, 0.12), 0px 0px 0px 2px rgba(0, 108, 235, 0.7)' }
  },
  cardMInner: {
    textDecoration: 'none',
    display: 'flex',
    flexGrow: 1,
    backgroundColor: '#ffffff',
    minWidth: 0,
  },
  cardMImage: {
    width: '132px',
    height: '132px',
    flexShrink: 0,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundImage: 'url("data:image/svg+xml;charset=US-ASCII,%3Csvg%20width%3D%22239%22%20height%3D%22186%22%20viewBox%3D%220%200%20239%20186%22%20fill%3D%22none%22%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%3E%0A%3Cpath%20fill-rule%3D%22evenodd%22%20clip-rule%3D%22evenodd%22%20d%3D%22M239%20186L146%200L92.5%20107L66%2054L0%20186H53H132H239Z%22%20fill%3D%22white%22/%3E%0A%3C/svg%3E%0A")',
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'center center',
    backgroundColor: '#F3F3F3',
    position: 'relative',
    '@media screen and (max-width: 350px)': {
      width: '80px',
      height: '80px',
    },
    ':before': {
      display: 'block',
      width: '100%',
      paddingTop: '100%',
      content: '\'\'',
    },
  },
  cardMImageInner: {
    position: 'absolute',
    content: '\'\'',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    '> img': {
      width: '100%',
      height: '100%',
      objectFit: 'cover',
    },
  },
  cardMRouteStatus: {
    position: 'absolute',
    content: '\'\'',
    top: '10px',
    left: 0,
    '@media screen and (max-width: 340px)': {
      left: '-12px',
      top: '-12px',
    },
  },
  cardMInfo: {
    width: '100%',
    paddingLeft: '12px',
    backgroundColor: '#ffffff',
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  cardMHeader: {
    overflow: 'hidden',
    width: '100%',
    minWidth: 0,
  },
  cardMFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    marginTop: 'auto',
  },
  cardMNumber: {
    fontSize: '16px',
    fontFamily: 'GilroyBold, sans-serif',
    color: '#1f1f1f',
    marginRight: '20px',
    lineHeight: '1.3em',
  },
  cardMTitle: {
    fontSize: '16px',
    color: '#1f1f1f',
    marginTop: 0,
    marginBottom: 0,
    textDecoration: 'none',
    fontFamily: 'GilroyBold, sans-serif',
    fontWeight: 'normal',
    whiteSpace: 'nowrap',
    width: 'auto',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    height: '24px',
    lineHeight: '1.3em',
    minWidth: 0,
  },
  cardMDate: {
    fontSize: '10px',
    color: '#B4BABC',
    textDecoration: 'none',
    display: 'inline-flex',
    alignItems: 'center',
    lineHeight: '16px',
  },
  cardMDateEndSoon: {
    color: '#E24D4D',
  },
  cardMDateIcon: {
    width: '8px',
    height: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: '6px',
    marginTop: '-1px',
    '> svg': {
      width: '100%',
      height: '100%',
      fill: '#D5DADC',
    },
  },
  cardMDateIconEndSoon: {
    '> svg': {
      width: '100%',
      height: '100%',
      fill: '#E24D4D',
    },
  },
  cardMComplexity: {
    display: 'flex',
  },
  cardMHook: {
    width: '19px',
    height: '19px',
    backgroundColor: '#28292A',
  },
  cardMDone: {
    opacity: '.7',
    ':hover': { boxShadow: '0px 4px 8px rgba(0, 0, 0, 0.08)' },
  },
  cardMRouteHoldsColor: {
    width: '19px',
    height: '19px',
    boxShadow: '0 0 1px rgba(0,0,0,0.7)',
    marginLeft: '12px',
  },
});

export default styles;
